FROM python:3.13-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    gcc \
    libmagic-dev \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
COPY ./requirements/base.txt ./
COPY ./requirements/dev.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r dev.txt
COPY . .
CMD ["./bin/start"]
